--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create box
local box = ccui.Layout:create()
box:ignoreContentAdaptWithSize(false)
box:setClippingEnabled(false)
box:setBackGroundColorType(1)
box:setBackGroundColor({r = 150, g = 200, b = 255})
box:setBackGroundColorOpacity(0)
box:setTouchEnabled(true);
box:setLayoutComponentEnabled(true)
box:setName("box")
box:setTag(643)
box:setCascadeColorEnabled(true)
box:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(box)
layout:setSize({width = 100.0000, height = 60.0000})
layout:setRightMargin(-100.0000)
layout:setTopMargin(-60.0000)
Node:addChild(box)

--Create txt
local txt = ccui.Text:create()
txt:ignoreContentAdaptWithSize(true)
txt:setTextAreaSize({width = 0, height = 0})
txt:setFontSize(50)
txt:setString([[1]])
txt:setLayoutComponentEnabled(true)
txt:setName("txt")
txt:setTag(639)
txt:setCascadeColorEnabled(true)
txt:setCascadeOpacityEnabled(true)
txt:setAnchorPoint(0.0000, 0.5000)
txt:setPosition(7.6936, 29.3358)
txt:setOpacity(130)
txt:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txt)
layout:setPositionPercentX(0.0769)
layout:setPositionPercentY(0.4889)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(0.8333)
layout:setSize({width = 25.0000, height = 50.0000})
layout:setLeftMargin(7.6936)
layout:setRightMargin(67.3064)
layout:setTopMargin(5.6642)
layout:setBottomMargin(4.3358)
box:addChild(txt)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

